core/util/BoostLog.cpp, core/util/BoostLog.h, core/util/OldLog.h
helps prevent crashes like #40
=> make LogStream more multithreading tolerant

core/util/BoostLog.cpp, core/util/BoostLog.h, core/util/Log.h, core/util/OldLog.h, core/util/PrintLog.cpp, core/util/PrintLog.h
please test before merging as to not break master more
=> un-break master

src/core/transport/SSUSession.cpp
=> don't send ssu packets if they are too big

src/client/Daemon.cpp, src/core/util/Log.cpp
* Minor style refactor in logger
=> Add core/util/Log.h to Daemon.cpp. Fixes #85.

src/client/Daemon.h, src/core/transport/Transports.cpp
These were also fixed in i2pd.
=> Two minor fixes

src/core/RouterContext.cpp, src/core/Version.h
=> Remove coreVersion + stat_uptime. Bump to 0.9.24.

src/app/Daemon.cpp, src/client/ClientContext.cpp, src/client/I2PTunnel/I2PTunnel.cpp, src/core/I2NPProtocol.cpp, src/core/NetworkDatabase.cpp, src/core/Reseed.cpp, src/core/RouterContext.cpp, src/core/Version.h, src/core/crypto/Rand.h, src/core/transport/Transports.cpp, src/core/util/HTTP.cpp, src/tests/benchmarks/Crypto.cpp, src/tests/unit_tests/Base64.cpp, src/tests/unit_tests/Utility.cpp, src/tests/unit_tests/crypto/AES.cpp, src/tests/unit_tests/crypto/DSA.cpp, src/tests/unit_tests/crypto/EdDSA25519.cpp, src/tests/unit_tests/crypto/ElGamal.cpp
* Resolve all using-directive TODO's
* I2NP/NetDb: move NETWORK_ID to Version.h
Note: I would wait to PR but since I want to move onto other topics (for the next PR), I would prefer to do topic-related PRs for now when possible.
=> Refactoring / Resolve using-directive TODO's

src/app/Daemon.cpp, src/app/Main.cpp, src/app/util/Config.cpp, src/app/util/Config.h, src/app/util/Filesystem.cpp
=> Config: implement single-switch opts, refactor.

README.md
---
Updates and enhances attribution, per discussion in ```#i2pd-dev```
=> updated readme to enhance attribution

src/core/Version.h
---
As stated in #161: tickets #149, #141, and #65 have been resolved - so now we should bump.
=> Version: bump to .25. Add pre-alpha. Closes #161.

CMakeLists.txt, src/core/crypto/AES.h, src/core/crypto/pimpl/cryptopp/AES.cpp, src/core/crypto/pimpl/cryptopp/Tunnel.cpp
---
Crypto: implement runtime AES-NI. Resolves #73.
=> Crypto: implement runtime AES-NI. Resolves #73.

.travis.yml, README.md, doc/FAQ.md
=> Development: update README/FAQ/Travis/Coverity

src/client/I2PTunnel/HTTPProxy.cpp, src/client/I2PTunnel/HTTPProxy.h
=> HTTPProxy: implement User-Agent scrubber + refactor / document code.

.travis.yml, src/app/Daemon.cpp, src/app/util/Config.cpp, src/app/util/Filesystem.cpp, src/app/util/Filesystem.h, src/client/AddressBook.cpp, src/client/I2PControl/I2PControl.cpp, src/client/I2PControl/I2PControl.h, src/client/I2PControl/I2PControlServer.cpp, src/client/I2PControl/I2PControlServer.h, src/client/I2PTunnel/HTTPProxy.cpp, src/client/I2PTunnel/SOCKS.h, src/client/Streaming.cpp, src/core/Garlic.cpp, src/core/Garlic.h, src/core/Identity.cpp, src/core/Identity.h, src/core/LeaseSet.cpp, src/core/LeaseSet.h, src/core/Version.h, src/core/transport/NTCPSession.h, src/core/transport/SSUData.cpp, src/core/util/Filesystem.cpp, src/core/util/Filesystem.h, src/tests/unit_tests/core/crypto/Rand.cpp
=> Misc: Garlic/LeaseSet/Filesystem/I2PControl refactoring + Travis/Coverity + bump to 0.9.26

.travis.yml
---
Referencing https://github.com/travis-ci/travis-ci/issues/6158
=> Travis: attempt to fix Coverity. Refs #199.

.travis.yml
=> Travis: add certs. Refs travis-ci/travis-ci#6142

.travis.yml
---
Another attempt to fix #199.
=> Travis: grab Coverity cert manually. Refs travis-ci/travis-ci#6142

src/core/Reseed.cpp
---
Refactors #220 (as we move away from macros when possible).
Also:
* Add documentation note
* Removes ALPHA macro
=> Reseed: fix literal-suffix warning. Refs #220.

doc/CONTRIBUTING.md
---
Needed to PR something in response to #227.
=> Docs: fix trivial numbering in contributing guide.

.github/PULL_REQUEST_TEMPLATE.md
---
* Fixes #232
* Also, clarify confirmation instructions
=> Docs: update pull-request template's license caveat.

README.md
=> Docs: add license status-badge + cleanup quickstart

README.md
---
* Cleanup/clarify other areas
* Linearize 'Acknowledgements' timeline
=> Docs: add contact info to README. Refs #241.

.travis.yml, Makefile
---
* Add FORCE_CLEAN env variable
=> Build: fix travis error from timeout. Refs #249.

Makefile
=> Build: fix shell'ism issue with travis. Refs #250.

.travis.yml, CMakeLists.txt, Makefile, README.md, doc/BUILDING.md
---
A TODO worth reiterating, as noted in …
=> Build: implement make install-resources + update docs. Fixes #45.

README.md, doc/FAQ.md
---
* Updates outdated information
* Clarifies other areas of questionable …
=> Docs: first-draft update of FAQ. Resolves #255.

.travis.yml
=> Build: experiment with cov-configure in Travis-CI

.travis.yml
=> Build: remove Coverity from Travis-CI. Closes #209

src/client/AddressBook.cpp, src/core/util/HTTP.cpp, src/core/util/HTTP.h, src/tests/unit_tests/core/util/HTTP.cpp
---
* Implement cpp-netlib
* Add test-case to unit-test
=> HTTP: rewrite URI parser. Fixes #257

.travis.yml, Makefile, doc/BUILDING.md
=> Build: fix + refactor Makefile + Travis CI + amend docs

src/app/util/Config.cpp
---
Without this, reseed options won't be listed in ```--help-with all```
=> Config: add reseed to cli help options.

.travis.yml
---
Attempt to fix IRC notifications.
* "always" is default
=> Travis CI: remove on_success/on_failure

.github/PULL_REQUEST_TEMPLATE.md, README.md, doc/ACKNOWLEDGEMENTS.md, doc/CONTRIBUTING.md
=> Docs: update to reflect drop of branch development + add acknowledgements

src/core/crypto/pimpl/cryptopp/util/Compression.cpp
---
Requires #272 to be merged.
* Referencing #141 and #272
=> Crypto: remove compression patch for cryptopp

Makefile
---
* No conflicts with GCC
* Closes #175
=> Makefile: add flags for cryptopp clang support

.travis.yml, Makefile, doc/BUILDING.md
---
Travis CI may take a few attempts to get right because of our gcc5 requirement.
=> Build: add clang to docs + Travis CI

.clang-format, doc/STYLE.md
=> Docs: update .clang-format + update style guide

.travis.yml, Makefile
=> Build: run tests after successful make tests build

CMakeLists.txt, Makefile
=> Build: reduce build time + Makefile cleanup/fixes

.travis.yml, doc/BUILDING.md
=> Update build docs for Trusty 14.04 + remove clang from Travis CI

src/client/AddressBook.cpp
=> mingw doesn't like c_str here

Makefile, doc/BUILDING.md, src/app/DaemonWin32.cpp, src/app/Win32Service.cpp, src/app/util/Filesystem.cpp
---
Note: mingw build still fails on linkage
=> Build: fix compilation on mingw-w64. Refs #36

.travis.yml
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monero-project/kovri/289)
=> Configure clang with gcc 4.9 on Travis-CI

doc/FAQ.md
=> Update dead link.

doc/BUILDING.md, doc/STYLE.md
=> Docs: update minimum requirements + instructions

CMakeLists.txt
---
Minium requirement error messages are now fatal.
=> Build: add compiler + boost minimum requirements to CMake

Makefile, doc/BUILDING.md
---
- Add FreeBSD building instructions
- Add BSD support for make install-resources
- Add git minimum requirement (for new BSD installs)
=> Build: reinstate FreeBSD build. Resolves #176

src/app/Daemon.cpp, src/app/Daemon.h, src/client/I2PTunnel/HTTPProxy.h, src/core/Garlic.cpp, src/core/RouterContext.cpp, src/core/RouterInfo.cpp, src/core/RouterInfo.h, src/core/transport/NTCPSession.cpp, src/core/transport/UPnP.cpp, src/core/tunnel/TunnelConfig.cpp
---
Some work on issue #263.
If I don't add many commits in the next few days, that means it will probably take about a week before I can do some more work.
=> Fixing coverity issues (#263).

.travis.yml, Makefile
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/monero-project/kovri/309)
=> Configure OS X build on Travis-CI

pkg/kovri.conf, src/app/daemon.cc, src/app/daemon.h, src/app/daemon_linux.cc, src/app/daemon_win32.cc, src/app/util/config.cc, src/app/util/config.h, src/app/util/filesystem.cc, src/core/util/filesystem.cc, src/core/util/filesystem.h, src/core/util/log.h, src/core/util/pimpl/log.cc
---
Also includes cleanup and related work in #214.
Note: not included in the comment for 85415fe was the new option ```--log-file-name``` for custom log name/location. Default is …
=> Log + Config: implement file logging + config options. References #214

pkg/kovri.conf, src/app/util/config.cc, src/app/util/config.h
---
References #214, #256, and #314
=> Config: refactor command-line handler + update/document config file

.travis.yml
=> Build: remove CXXFLAGS from Travis CI. Refs #316

README.md, doc/BUILDING.md, doc/FAQ.md
=> Docs: various updates and cleanup of building documentation

doc/CONTRIBUTING.md, doc/QUALITY_ASSURANCE.md
---
We're pulling #58 apart in an attempt to streamline a QA model.
```
&anonimal | rakhimov: solmar and I were discussing a better way to approach monitoring and implementing a quality …
```
=> Docs: implement Quality Assurance guide. Refs #58

doc/BUILDING.md
---
They are reportedly not accurate and won't be maintained
=> Docs: remove EC2 build instructions

src/client/datagram.cc
---
This is a Coverity reported leak,
which seems to be false positive.
The current refactoring is to make the code easier on Coverity.
---
This change is [<img …
=> Deal with Datagram msg leak false-positive

src/core/util/log.h, src/core/util/pimpl/log.cc
=> Log: various fixes (Coverity + Clang warnings)

.travis.yml
---
A little nicer approach with Travis add-ons for ppa sources.
=> Simplify Boost fetch on Travis configuration

src/app/daemon.cc, src/app/util/config.cc, src/core/router_context.cc, src/core/router_context.h, src/core/transport/ntcp.cc, src/core/transport/ntcp_session.cc, src/core/transport/transports.cc, src/core/transport/transports.h
---
Adds `--enable-ntcp` and `--enable-ssu` (#184)
Seems to fix the most critical issues listed in #187.
Fixes #334.
=> Add transport options, fix various NTCP bugs

src/core/util/mtu.cc
---
This fixed CID 146759.  Will also work on refactoring this old c style code.
=> MTUCHECK :: fix CID146758

src/core/crypto/aes.h, src/core/transport/ntcp_session.cc, src/core/transport/ntcp_session.h
---
Fixes a few NTCP-related bugs.
```
<+EinMByte> anonimal: Ok, so I don't want to fix this, or I think it requires more structural changes.
<+EinMByte> I propose to PR what I have so far …
```
=> Several NTCP-related fixes

pkg/kovri.conf, src/app/daemon.cc, src/app/main.cc, src/app/util/config.cc, src/client/CMakeLists.txt, src/client/i2p_control/i2p_control.cc, src/client/reseed.cc, src/client/reseed.h, src/client/util/http.cc, src/client/util/http.h, src/client/util/zip.cc, src/client/util/zip.h, src/core/CMakeLists.txt, src/core/net_db.cc, src/core/net_db.h, src/core/router_context.cc, src/core/router_context.h, src/core/transport/ntcp.cc, src/core/util/mtu.cc, src/core/util/mtu.h
=> Misc: MTU/NTCPServer/NetDb/Reseed/HTTP/ZIP/App/Package

src/client/destination.cc
---
Fixes one of the segfaults upon SIGINT
References #342
=> Destination: delete tunnel pool outside of dtor

src/client/address_book.h, src/client/streaming.cc, src/client/util/http.cc
---
@EinMByte peer review appreciated before merge.
=> Client: resolve a few medium Coverity defects

.codedocs
---
CodeDocs is currently useless. If this update has no effect, we should simply remove the feature (we have a `make doxygen` option).
=> Doxygen: update codedocs config

src/client/i2p_tunnel/socks.cc, src/client/streaming.cc, src/core/identity.cc, src/core/transport/ssu.cc, src/core/transport/ssu.h
=> Coverity: resolve all (presently) remaining UNINIT_CTOR

src/client/client_context.h, src/core/identity.cc, src/core/transport/upnp.cc, src/core/tunnel/tunnel_config.cc, src/core/util/mtu.cc
---
Not noted in f0de48f is defect type `OVERRUN`.
References #263.
=> Coverity: resolve medium + high defects. Refs #263

src/app/daemon_linux.cc
- [x ] I confirm.
---
Coverity fix cid135926
=> COVERITY :: see #263 ; cid135926

src/app/CMakeLists.txt, src/core/util/mtu.cc
=> Build: fix compilation on windows/mingw-w64 (MTU)

README.md
---
The previous IPA appeared to be completely inaccurate (depending on dialect).
=> Docs: update IPA in README

pkg/certificates/ssl/reseed.atomike.ninja.crt, src/client/util/http.cc
=> HTTP: update SSL options + set ciphers, update cert symlink

README.md, doc/BUILDING.md, doc/FAQ.md, doc/USER_GUIDE.md, pkg/tunnels.conf, src/app/util/config.h
=> Docs/Package: provide rudimentary end-user docs + document and update tunnels.conf

src/app/daemon.cc, src/client/client_context.cc, src/client/client_context.h
---
Tested and confirmed fix. Client/server tunnel functionality remains intact over clearnet.
---
- Design and logic refactor
- Create function for creating private keys
=> ClientContext: refactor private key handling. Fixes #391

.gitmodules
=> Deps: update cpp-netlib/cryptopp submodules

.gitmodules
=> Deps: update cryptopp submodule to 5.6.5. Refs #370

doc/BUILDING.md, doc/USER_GUIDE.md
---
Added recommendation to users behind a restrictive NAT router.
=> Added recommendation for users behind a NAT

doc/BUILDING.md
---
Further testing needed, but from #403 we should probably suggest minimum RAM requirements.
=> Add note about suggested RAM requirements

Makefile
---
It appears to no longer be needed.
=> Build: remove cryptopp clang hack in Makefile

src/core/i2np_protocol.cc, src/core/i2np_protocol.h, src/core/net_db.cc, src/core/net_db_requests.cc, src/core/net_db_requests.h, src/core/transport/ssu_data.cc, src/core/tunnel/transit_tunnel.cc, src/core/tunnel/transit_tunnel.h, src/core/tunnel/tunnel.cc, src/core/tunnel/tunnel.h, src/core/tunnel/tunnel_base.h, src/core/tunnel/tunnel_config.cc, src/core/tunnel/tunnel_config.h, src/core/tunnel/tunnel_endpoint.cc, src/core/tunnel/tunnel_endpoint.h, src/core/tunnel/tunnel_gateway.cc, src/core/tunnel/tunnel_gateway.h, src/core/tunnel/tunnel_pool.cc, src/core/tunnel/tunnel_pool.h
=> NetDB/I2NP/Tunnels: refactor local variable style per contributing guide

src/app/daemon.cc, src/app/daemon_win32.cc, src/app/win32_service.cc, src/app/win32_service.h, src/client/datagram.cc, src/client/datagram.h, src/client/destination.cc, src/client/destination.h, src/client/i2p_service.cc, src/client/i2p_service.h, src/client/i2p_tunnel/i2p_tunnel.cc, src/client/i2p_tunnel/i2p_tunnel.h, src/client/i2p_tunnel/socks.cc, src/client/i2p_tunnel/socks.h, src/client/streaming.cc, src/client/streaming.h, src/core/crypto/signature.h, src/core/crypto/tunnel.h, src/core/garlic.h, src/core/identity.cc, src/core/profiling.cc, src/core/profiling.h, src/core/transport/ntcp_session.cc, src/core/transport/ntcp_session.h, src/core/transport/transports.cc, src/core/transport/transports.h, src/core/transport/upnp.cc, src/core/util/base64.cc, src/core/util/base64.h, src/core/util/mtu.cc
=> Global style refactor for local variables per contributing guide

src/core/net_db.cc
=> NetDB: refactored redundant code checking file path

src/client/api/streaming.cc, src/client/api/streaming.h, src/client/proxy/socks.cc
=> SOCKSProxy: refactored and documented per the contributing guide

README.md
=> README: updates + add badge + fix wrong build link

Makefile
=> Build: don't build cryptopp shared object

src/client/service.h
=> Service :: add comments to service.h document base classes

README.md, doc/BUILDING.md
=> Docs: update build links + OS info + build doc

src/app/daemon_win32.cc, src/app/util/filesystem.cc, src/app/win32_service.cc, src/core/util/filesystem.cc, src/core/util/mtu.cc
---
- Mostly broken by ecd3c97b and 8b5944d (#410)
- Moves filesystem MinGW fix from app (611aa8c 36b26b5)
- Also includes new WIN32_LEAN_AND_MEAN fix for core
- Does not resolve dynamic …
=> Build: fix win compilation (not win link). Refs #36

README.md
---
- Updates ARMv7/8 OS info and links
- Puts existing coverage into a matrix
=> README: update build links, add coverage matrix

README.md
---
References https://github.com/monero-project/monero/issues/903
=> README: add Meta repo link for non-code issues

src/core/router/info.cc, src/core/router/transports/ssu/packet.h, src/core/router/transports/upnp.h, src/core/router/tunnel/config.cc
=> Coverity: various router fixes

src/client/address_book/impl.cc
---
Noticed upon reviewing CID 151160/2/6, control was never allowed to
reach the loading of publishers if a subscription was already loaded at
startup - thus publishers were never loaded.
In …
=> AddressBook: fix two publisher/subscription-related bugs. Fixes #445 #446

src/core/router/transports/ssu/server.cc
---
References CID 151157 151159. Ideally we would only annotate std::bind
(if that were possible), but let's see if coverity can figure this out.
Also added brief notes.
=> SSUServer: add coverity function annotations. Refs #263

README.md
---
References #90 and monero-project/meta#9
=> README: add links for Monero's GitLab mirror + hosted build services + FFS sticky

README.md, doc/FAQ.md, doc/USER_GUIDE.md
=> Docs: add Moneropedia link + cleanup doc/dev language

src/client/util/http.cc
---
See comment here: https://github.com/monero-project/kovri/issues/453#issuecomment-260161125
Fixes #453. References https://github.com/cpp-netlib/cpp-netlib/issues/696
=> HTTP: apply cpp-netlib patch for windows exception

src/core/router/net_db/impl.cc, src/core/router/net_db/requests.cc
=> NetDb: std::array refactor + minor local variable name refactor + trivial formatting. Refs #444

src/client/api/datagram.cc, src/client/api/datagram.h, src/client/api/streaming.cc, src/client/api/streaming.h, src/client/destination.cc, src/client/destination.h, src/core/router/context.cc, src/core/router/context.h, src/core/router/garlic.cc, src/core/router/i2np.cc, src/core/router/i2np.h, src/core/router/net_db/impl.cc, src/core/router/net_db/requests.cc, src/core/router/transports/impl.cc, src/core/router/transports/impl.h, src/core/router/transports/ntcp/session.cc, src/core/router/transports/ntcp/session.h, src/core/router/transports/ssu/data.cc, src/core/router/transports/ssu/data.h, src/core/router/tunnel/base.h, src/core/router/tunnel/endpoint.cc, src/core/router/tunnel/gateway.cc, src/core/router/tunnel/impl.cc, src/core/router/tunnel/impl.h, src/core/router/tunnel/transit.cc, src/core/router/tunnel/transit.h
=> I2NP: resolve namespace TODO + message type trivial style refactor Refs #462

src/client/address_book/impl.cc, src/client/address_book/impl.h
=> AddressBook: fix segfault if subscription file is missing + create download wrapper for subscriber

src/core/router/transports/ssu/packet.cc
=> SSU: handle unknown payload types + resolve build warnings

README.md, doc/FAQ.md
=> Docs: clarify development status in relation to monero

src/app/CMakeLists.txt
=> Build: fix CMake policy CMP0054 warning

src/app/daemon.h, src/app/daemon_linux.cc
---
- Exit gracefully for various errors:
- if setting session ID fails
- if pid file cannot be written
- Don't attempt to remove pid file if it doesn't exist
- Datatype / initialization …
=> DaemonLinux: fix pid file handler + various refactoring

src/core/util/byte_stream.h
---
Returns underlying type of enumerator, helps with scoped enumerations
References #158 #450
=> ByteStream: create helper template for enum types. Refs #450

src/core/router/transports/ssu/data.cc, src/core/router/transports/ssu/data.h, src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/packet.h, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc, src/core/router/transports/ssu/session.h, src/core/util/byte_stream.h
---
SSU: refactor casting of enum types. Refs #140 #158 #450
=> SSU: refactoring of enum types. Refs #140 #158 #450

src/app/daemon.cc, src/app/daemon.h, src/app/daemon_linux.cc, src/app/daemon_win32.cc, src/app/main.cc, src/app/util/config.cc, src/app/util/config.h, src/app/util/filesystem.cc
---
Fixes #312, closes #214, references #98
=> Daemon/App: initialize contexts *after* fork + various refactoring. Fixes #312

README.md
---
We had many great meetings that took logo development into wonderful new directions: many laughs, many tears, and an all-around educational experience.
After reviewing where we started …
=> README: add Kovri logo. Resolves #282

src/client/util/http.cc
=> HTTP: extend cpp-netlib exception patch to all platforms

src/app/instance.cc, src/app/instance.h
---
Instance: fix member initialization + move ctor impl. Resolves #494
=> Instance: fix member initialization + move ctor impl. Resolves #494

README.md
---
Also, trivial related cleanup.
=> README: add Kovri I2P mirror (GitLab). Closes #90

src/core/crypto/impl/cryptopp/signature.cc
---
Noticed when opening #498. Unit-tests + live tests pass.
=> RSARawVerifier: minor refactoring (datatype / logic / style). Refs #498

doc/CONTRIBUTING.md, doc/QUALITY_ASSURANCE.md
---
Also updates QA guide
Closes #158
=> Docs: add compliance note to contributing guide. Closes #158

src/core/router/i2np.h, src/core/router/tunnel/config.cc, src/core/router/tunnel/config.h, src/core/router/tunnel/impl.cc, src/core/router/tunnel/impl.h, src/core/util/byte_stream.cc, src/core/util/byte_stream.h
---
Regarding #355, if the issue is a null router info, this branch should deal appropriately. If (as mentioned in ticket) the issue is indeed a null router identity, then I'll need a real …
=> TunnelHopConfig + I/O ByteStream: fixes + refactoring + documentation. Closes #355

src/client/address_book/impl.cc, src/client/address_book/impl.h, src/client/address_book/storage.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/client/address_book/impl.cc
=> AddressBook: more hardening + improve subscription impl + unit-test + refactoring

src/app/config.cc, src/client/address_book/impl.cc, src/client/api/datagram.cc, src/client/api/streaming.cc, src/client/reseed.cc, src/client/util/parse.cc, src/core/crypto/impl/cryptopp/rand.cc, src/core/crypto/rand.h, src/core/router/lease_set.cc, src/core/router/transports/impl.cc, src/core/router/transports/ssu/server.cc, src/core/router/tunnel/gateway.cc, src/core/router/tunnel/impl.cc, src/core/router/tunnel/pool.cc, tests/unit_tests/core/crypto/dsa.cc, tests/unit_tests/core/crypto/elgamal.cc, tests/unit_tests/core/crypto/rand.cc
*By submitting this pull-request, I confirm the following:**
---
Closes #317 
Resolves #515
=> Crypto: re-implement random range + improve unit-test + refactoring. Closes #317 + #515

src/app/daemon.cc
=> DaemonSingleton: catch base std::exception when start/stop

README.md, doc/BUILDING.md, doc/STYLE.md, doc/USER_GUIDE.md
=> Docs: misc updates to readme/build/style/user-guide

src/client/address_book/impl.cc, src/client/address_book/impl.h, src/client/address_book/storage.h
=> AddressBook: fix subscription host writing bug + refactor

src/client/util/http.cc
=> HTTP: strengthen OpenSSL cipher list and options

.dockerignore, Dockerfile, doc/BUILDING.md, doc/USER_GUIDE.md
=> Introduce Dockerfile

src/core/router/transports/ntcp/server.cc, src/core/router/transports/ntcp/session.cc, src/core/router/transports/ntcp/session.h, src/core/util/byte_stream.cc, src/core/util/byte_stream.h
---
Contributes to #352 while working towards finishing #187. Rebasing + PR'ing now since other kovri contributors have returned from hiatus (in case they want to work on #187).
=> NTCP: refactoring + phase info debugging

src/client/context.cc, src/client/context.h
=> ClientContext: write client/server local b32's to text file(s) + improve private keys impl

README.md
---
Prevents failing PR's from advertising incorrect repo master branch build status.
=> README: use static builds for build status + add link

Makefile
---
Requires updating cryptopp submodule to latest tagged release in order to utilize CMake disabling of `-march=native` (for cryptopp).
=> Build: refactor + cleanup Makefile

doc/BUILDING.md, doc/USER_GUIDE.md
=> Docs: various additions to the user guide

Makefile
=> Makefile: add missing bracket in android target

Makefile
- [ x] I confirm.
---
output compile_commands.json upon build.  for use with youcompleteme / vim
=> VIM :: makefile output compile_commands.json

README.md, doc/BUILDING.md
=> Docs: update FreeBSD build instructions + build status

doc/STYLE.md
=> Docs: update cpplint download link in style guide

CMakeLists.txt, src/CMakeLists.txt, src/core/util/filesystem.h, src/util/CMakeLists.txt, src/util/base.cc, src/util/base.h, src/util/command.h, src/util/main.cc
=> kovri-util : add base32 base64

src/core/router/net_db/impl.cc, src/core/router/profiling.cc, src/core/router/profiling.h, src/core/util/filesystem.cc
---
Fixes #519. Fixes #520. We need #385.
=> NetDb/RouterProfile: fix implementation for RI + profile loading/saving/deleting

README.md, doc/QUALITY_ASSURANCE.md, doc/VULNERABILITY_RESPONSE_PROCESS.md
---
Based heavily on my work in (and the outcome of) https://trac.i2p2.de/ticket/1119
- Adds official VRP
- Updates Quality Assurance guide and README
References #225 and monero-project/meta#39
=> Docs: add Vulnerability Response Process

snap/snapcraft.yaml
=> Snapcraft: add CMake to build-packages

Makefile, src/app/CMakeLists.txt, src/core/util/i2p_endian.h
=> Kovri: introduce DragonFly BSD support

src/client/api/i2p_control/session.cc, src/core/router/tunnel/base.h, src/core/router/tunnel/impl.cc, src/core/router/tunnel/impl.h
=> TunnelBase: fix datatype/impl for creation time + related refactoring

src/app/config.cc, src/app/config.h, src/app/daemon.h, src/app/daemon_linux.cc, src/core/router/context.h, src/core/util/filesystem.cc
=> Config : add option --data-dir

src/util/main.cc
=> kovri-util : fix typedef ListCommands

README.md
=> README: update/add contact information + add emails

doc/VULNERABILITY_RESPONSE_PROCESS.md
=> Docs: add preamble to Vulnerability Response Process

doc/FAQ.md
=> FAQ: add "What does Kovri do/not do for you?"

src/client/address_book/impl.cc, src/client/util/http.cc, src/client/util/http.h, src/core/util/log.h
---
That has nothing to do with what i am doing currently, so dunno if it's appropriate to PR this.
=> http: const getters + split HostIsI2P and CompleteURI

Makefile, doc/BUILDING.md, pkg/kovri-install.sh
Also removes install-resources
---
---
Related to https://github.com/monero-project/kovri/issues/362
=> Build + docs: add `make install` + bash uninstaller and `make uninstall` + fix OSX packager

pkg/kovri-install.sh
Also adds uninstaller to help options
---
---
=> Installer: fix packager when specifying filename

src/client/reseed.cc, src/client/reseed.h, src/core/router/identity.cc, src/core/router/identity.h, src/core/util/filesystem.h, src/util/CMakeLists.txt, src/util/main.cc, src/util/su3file.cc, src/util/su3file.h
---
Referencing #399 
Still needs keygen, sign and bulksign
Edit: the windows build is fixed in the previous PR and this will need a rebase anyway
=> kovri-util: add su3file showversion, verifysig and extract

src/client/reseed.cc, src/client/reseed.h, src/util/main.cc, src/util/su3file.cc
=> kovri-util : remove data-dir and add cert-dir for su3file

src/core/router/identity.cc, src/core/router/identity.h, src/core/router/info.cc, src/core/router/info.h, src/core/util/filesystem.h, src/util/CMakeLists.txt, src/util/main.cc, src/util/routerinfo.cc, src/util/routerinfo.h, src/util/su3file.cc
=> kovri-util: add routerinfo

pkg/kovri-install.sh
=> Installer: fix packager for DragonFly BSD + related + misc

pkg/kovri-install.sh
=> Packager: use rsync for all supported BSD's

README.md, doc/BUILDING.md
=> Docs: add nightly build downloads + checksum links + info + misc

src/app/config.cc, src/app/config.h, src/app/daemon.cc, src/app/daemon.h, src/app/daemon_linux.cc, src/app/daemon_win32.cc, src/app/instance.cc, src/app/instance.h, src/client/context.cc, src/client/context.h, src/client/destination.cc, src/core/router/context.h, src/core/router/info.h, src/core/router/net_db/impl.cc, src/core/router/profiling.cc, src/core/router/transports/impl.cc, src/core/router/transports/session.h, src/core/router/transports/ssu/data.cc, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc, src/core/router/transports/upnp.cc, src/core/router/transports/upnp.h, src/core/router/tunnel/impl.cc, src/core/router/tunnel/impl.h, src/core/util/base64.cc, src/core/util/filesystem.h, src/core/util/queue.h
=> Add consts in various places where it makes sense

src/core/router/transports/ntcp/server.cc, src/core/router/transports/ntcp/session.cc
=> NTCP: ident hash logging fix + refactoring

pkg/kovri-install.sh
=> Installer: add OpenBSD to $OSTYPE check

doc/BUILDING.md
Thank you @danrmiller for getting this going
Referencing #590
---
---
=> Docs: add OpenBSD build instructions

pkg/kovri-install.sh
=> Installer: use sha256 command for OpenBSD packager

src/app/config.cc, src/app/instance.cc
=> Config: fix TODO move def port outside of ParseArgs

src/app/config.cc, src/app/instance.cc, src/app/instance.h, src/client/context.cc, src/client/context.h
---
---
Minor changes, just preparation for a future discussion on IRC.
Referencing #96
=> Minor client/server tunnel refactor

src/app/instance.cc, src/app/instance.h
---
---
Fix for tunnels who were not deleted if  type changed
Referencing #96
=> Instance: distinct tunnel containers for RemoveOldTunnels

src/app/config.cc, src/app/instance.cc, src/client/context.cc, src/client/tunnel.h
=> Instance: fixes for reload client tunnel

pkg/config/kovri.conf, src/app/config.cc
---
---
Not sure about this one, but makes sense to me
#96
=> Configuration: check user input port in valid range

src/client/context.cc, src/client/service.h
=> TCPIPAcceptor: remove redundant address

src/core/router/info.cc, src/util/routerinfo.cc
=> RouterInfo: check for large inputs

doc/VULNERABILITY_RESPONSE_PROCESS.md
=> Docs: update HackerOne link in VRP

src/CMakeLists.txt, src/app/CMakeLists.txt, src/util/CMakeLists.txt
=> Apps: refactor common cmake with kovri-util

src/core/util/filesystem.h, src/util/routerinfo.cc, src/util/su3file.cc
=> kovri-util: fix alloc-dealloc-mismatch

src/client/proxy/http.cc, src/client/util/http.cc, src/client/util/http.h, tests/unit_tests/client/util/http.cc
=> HTPP : replace decode with cpp-netlib decoded 

src/app/config.cc, src/app/instance.cc, src/client/reseed.cc, src/core/router/context.cc, src/core/router/context.h
=> Reseed: skip SU3 checks when reseed-from .zip

doc/BUILDING.md
=> Docs: add boost patches for OpenBSD

src/core/router/net_db/impl.cc
=> NetDb: initializations + log fixing

.gitmodules
=> Repo: point kovri-docs to monero-project, bump to 4086a9e

cmake/version.h.in, src/app/config.cc, src/app/instance.cc, src/core/router/context.cc, src/core/router/i2np.cc, src/core/router/info.h, src/util/routerinfo.cc, src/util/routerinfo.h
---
---
Ref #399 
Here is my script to start a testnet. Hopefully something is obviously wrong :) 
#!/bin/bash
for var in `seq 10 29`
do
mkdir router_$var
mkdir router_$var/.kovri
chown -R user:user router_$var
docker run -u 0 -w /home/kovri -it --rm -v …
=> kovri-util: add routerinfo create

contrib/scripts/docker_privatenet.sh
---
---
WIP (still doesn't work, but after #658 not sure anymore that it's related to this particular configuration)
JFTR, the next error looks like
[0x00007ffab4199ab0] [debug]  SSUServer: handling received data
[0x00007ffab4199ab0] [debug]  SSUServer: …
=> Contrib: add docker privatenet script

src/util/routerinfo.cc
=> kovri-util: fix uncaught exception for routerinfo create

Makefile
=> Build: re-introduce UPnP-only option to Makefile

src/app/config.cc, src/app/daemon.cc
---
---
Not sure it's the best fix, but the app didn't exits with the following mistake (stays hanging after return EXIT_FAILURE)
./build/kovri --host blabla
=> Daemon: call Stop on Init exception

src/core/router/transports/session.h, src/core/router/transports/ssu/session.cc
---
---
Ref #140 
Looks like we were appending SignedOnTime instead of replacing the previous.
=> SSU:  fix ProcessSessionConfirmed SignedOnTime

contrib/docker/Dockerfile, contrib/docker/testnet.sh
Also bumps Alpine to 3.6 (resolves #668)
---
---
=> Testnet: implement read env options + image build + various refactoring

contrib/docker/Dockerfile
---
---
This PR should bring the size of the image from ~1.5GB to 135MB. There's still probably some that I can remove, but it's a good decrease for now.
=> slim dockerfile

README.md
=> Docs: bump to kovri-docs a43f9c5a + update README

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> Repo: update broken links + language in templates and README

src/core/router/transports/ssu/data.h, src/core/router/transports/ssu/packet.h
=> SSU: Better definition of buffer sizes

Makefile
DISABLE_NATIVE_ARCH was removed upstream and a flag to enable native
build was never implemented.
Also extends native flag to cpp-netlib and kovri + static build.
Resolves #692.
---
---
=> Build: remove/add native option, bump cryptopp

contrib/docker/Dockerfile, contrib/docker/testnet.sh
=> Testnet: fixes + features + refactoring

Makefile
Target notes are suggested for monero-project/kovri-docs#12
---
---
=> Makefile: remove deprecation/dead code, add target notes

pkg/installers/kovri-install.sh, pkg/kovri-bash.sh
=> Installer: add bash completion script as package resource

README.md
Referencing monero-project/meta#116.
---
---
=> README: update vulnerability response

.gitmodules
=> Deps: bump kovri-docs + remove cryptopp tag from submodule

contrib/docker/testnet.sh
@MoroccanMalinois let's hold on merging until we figure out why docker appears to not auto-flush the pipe (docker appears to only flush once the instance is stopped).
Note: #706 confirms that auto-flushing works (at least on mainnet).
---
---
=> Testnet: create named pipes for log output + refactor RI and container creation + logic layout refactor

README.md
=> README: update twitter handle, add mastodon

contrib/docker/testnet.sh
=> Testnet: add env var help usage + log monitoring to usage help

Makefile, cmake/FindCryptoPP.cmake
Resolves #699. Resolves #719.
---
---
=> Build: bump cryptopp revision + cryptopp build-related + disable cryptopp SIGILL probes

contrib/docker/testnet.sh
=> Testnet: read/add env for container stop timeout

pkg/config/kovri.conf, src/app/config.cc, src/core/util/log.cc, src/util/main.cc
=> Log: add colored severity levels

src/core/util/log.cc
=> Log: align after severity

contrib/docker/Dockerfile, contrib/docker/testnet/dockerfiles/Dockerfile.alpine, contrib/docker/testnet/testnet.sh
=> Docker: add bash to alpine instance and minor testnet fix

src/client/tunnel.cc, src/client/util/parse.cc, src/client/util/parse.h, tests/unit_tests/client/util/parse.cc
=> Client: remove CSV parser + refactor ACL parsing impl + add ACL parsing unit-test

src/util/main.cc
=> kovri-util: small cosmetic changes + simplify two checks

contrib/docker/testnet/dockerfiles/Dockerfile.arch
=> Testnet: add system/net utilities to Arch Dockerfile

contrib/testnet/testnet.sh
=> Testnet: fix path for kovri bash completion

contrib/python/CMakeLists.txt, contrib/python/example.py, contrib/python/instance.h, contrib/python/util.cc, contrib/python/util.h, src/app/daemon.cc, src/client/instance.cc, src/client/instance.h, src/util/kovri.cc
WIP towards resolving #350 and #351.
---
---
=>  Boost.Python: implement core/client wrappers + utils and add kovri python example

contrib/testnet/testnet.sh
=> Testnet: start, stop and destroy webserver

src/core/router/net_db/impl.cc
=> NetDb: fix logging of peer hash count for DatabaseSearchReply

README.md
- Bounty will be awarded during Beta releases
- Referencing monero-project/meta#142
Referencing monero-project/meta#83
---
---
=> README: remove line regarding bounty

src/core/util/config.cc
`[2017-11-04 01:22:00] <anonimal> selsta: it was probably just missed, I don't know`
---
---
=> Core: replace stray cout in config

src/core/router/garlic.cc
=> Garlic: fix crash on trace logging

src/core/router/info.cc, src/core/router/info.h, src/util/i2pcontrol.cc, src/util/main.cc, src/util/routerinfo.cc
=> kovri-util: remove useless options and use new RI ctor interface

src/core/router/net_db/impl.cc, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc, src/core/router/transports/ssu/session.h
=> SSU: various fixes around peer testing

src/client/api/streaming.cc
Should resolve #767 until #498 and #755 are resolved.
---
---
=> Streaming: fix overflow if large sig is included

src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/session.cc, src/core/router/tunnel/config.cc, src/core/util/byte_stream.cc, src/core/util/byte_stream.h, src/core/util/i2p_endian.cc, src/core/util/i2p_endian.h, src/core/util/little_big_endian.h, tests/unit_tests/core/router/transports/ssu/packet.cc, tests/unit_tests/core/util/byte_stream.cc
plus related refactoring.
**Hold on merging until LE testing is complete**.
---
---
=> ByteStream: I/O reader/writer/endian rewrite

pkg/installers/kovri-install.sh
=> Installer: use Inno Setup on win `make install`

LICENSE.md
=> LICENSE.md: Update copyright date

README.md
=> README: section reorg + cleanup

src/core/router/context.cc, src/core/router/context.h, src/core/router/transports/session.h, src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/packet.h, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc, src/core/router/transports/ssu/session.h, src/core/router/transports/upnp.cc, src/core/util/byte_stream.h, tests/unit_tests/core/router/transports/ssu/packet.cc, tests/unit_tests/core/util/byte_stream.cc
---
---
WIP for #140.
Live tests + unit-tests pass. I'd like to run the router for a while to observe new assertion behavior (they lead to some of the various fixes).
There are various existing issues and work to be done outside of the TODOs. I'll leave a note in #140.
=> SSU: fixes, rewrites, refactors, docs

src/core/util/byte_stream.cc, src/core/util/byte_stream.h
=> ByteStream: const cleanup + remove unused member

src/core/crypto/aes.h, src/core/crypto/util/x509.h, src/core/router/garlic.h, src/core/router/identity.h, src/core/router/info.h, src/core/util/tag.h
---
---
We'll eventually need a more useful and smarter `Tag`.
=> Tag: properly initialize, add size check, cleanup/refactor

src/client/address_book/impl.cc, src/client/address_book/storage.cc
---
---
Referencing #305 and anonimal's [advice](https://github.com/monero-project/kovri/pull/813#discussion_r169812054) on exception handling.
Unsure if test case for filesystem error [is appropriate](https://github.com/monero-project/kovri/pull/813#issuecomment-367224433), can …
=> AddressBook: add address to file I/O refactor + add exception handling

src/core/router/context.cc, src/core/util/config.cc, src/util/routerinfo.cc
---
---
Fixes #832. Fixes #836.
=> Kovri: arg fixes for transports

src/client/address_book/impl.cc, src/core/router/transports/ssu/data.cc, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc
=> Build: Fix build with Boost 1.67

src/client/address_book/impl.cc, src/client/address_book/impl.h, tests/unit_tests/client/address_book/impl.cc
=> AddressBook: Container for host-address entry

src/core/util/filesystem.h
=> Filesystem: clarify FileStream read/write docs

cmake/UseDoxygen.cmake
=> Build: fix Doxygen build

src/app/daemon_linux.cc, src/client/api/streaming.cc, src/core/util/config.h
=> Fix build warnings on GCC 5.4

src/client/api/i2p_control/data.h, src/client/instance.cc, src/client/instance.h, src/client/util/config.cc, src/client/util/config.h, src/core/instance.cc, src/core/instance.h, src/core/router/transports/upnp.h, src/core/router/tunnel/base.h, src/core/router/tunnel/pool.h, src/core/util/config.cc, src/core/util/config.h, src/util/cpuid.cc
=> Kovri: fix build warnings + broken gcc8 build

tests/unit_tests/CMakeLists.txt, tests/unit_tests/core/util/config.cc
=> Tests: Configuration::ListParameter unit-test

contrib/pkg/docker/Dockerfile, contrib/testnet/Dockerfiles/Dockerfile.alpine, contrib/testnet/Dockerfiles/Dockerfile.arch, src/util/routerinfo.cc
=> Testnet + Util: update + fix

CMakeLists.txt, src/app/win32_service.cc, src/app/win32_service.h, src/core/util/filesystem.cc, src/core/util/mtu.cc, src/core/util/tag.h
=> Build: fix mingw warnings

Makefile, pkg/installers/kovri-install.sh
Update recently changed files in 2018, include copyright update in
kovri-docs
---
---
=> Repo: update copyright dates + bump kovri-docs

contrib/pkg/docker/Dockerfile, contrib/testnet/testnet.sh
---
---
This isn't urgent because we're in the process of removing the docker testnet.
=> Contrib: change default Dockerfile repo name

src/core/util/tag.h
=> Tag: getter for tag size

CMakeLists.txt
=> CMake: build without RPATH

README.md
need to cd into the directory before building
---
---
=> Improved build instructions

tests/unit_tests/main.cc
Stops log spam when running unit-tests.
Resolves #918
---
---
=> Tests: disable libs' singleton logger

src/core/util/mtu.cc
=>  MTU: support local MTU size on DragnonFly BSD

pkg/config/kovri.conf
=> Fixing minor typos

src/util/main.cc
Mostly potential errors in parsing options or initializing objects.
Coverity #175241 #175244 #175254 #175258 #186209
The diff looks quite messy, but it's all just indenting the code and removing one short try/catch block in the middle.
---
- I give this submission freely under the BSD …
=> utils/main: catch all exceptions in main()

src/client/proxy/http.cc, src/client/proxy/http.h, tests/unit_tests/client/proxy/http.cc
=> HTTPProxy: improve HTTP error reporting

contrib/python/CMakeLists.txt
=> Build: add kovri_python cotire build 

CMakeLists.txt, Makefile
=> Build: don't skip rpath for in-tree shared deps

README.md
=> README: set `make release` as recommended default

src/client/context.cc, src/client/context.h
=> Client: create separate b32/b64 dest text files

README.md
By submitting this pull-request, I confirm the following:
I have read and understood the developer guide in kovri-docs.
I have checked that another pull-request for this purpose does not exist.
I have considered and confirmed that this submission will be valuable to others.
I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
I give this submission freely under the BSD 3-clause license.
Incredibly minor issue as outlined here: https://github.com/monero-project/kovri/issues/964
=> Made Readme languages be written in their language

src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/packet.h, src/core/util/byte_stream.cc
=> SSU: various fixes to fragment parser

src/client/proxy/socks.cc, src/client/proxy/socks.h
=> SOCKS: separate declarations from definitions

src/core/CMakeLists.txt, src/core/crypto/impl/cryptopp/signature.cc, src/core/crypto/impl/cryptopp/util/misc.cc, src/core/crypto/util/misc.h, src/core/router/i2np.cc, src/core/router/identity.h, src/core/router/transports/ssu/session.cc, src/core/router/tunnel/endpoint.cc, src/core/util/tag.h
---
---
Resolves #895. Please see notes in #895.
=> Kovri: use const-time comparison in security-critical areas

README.md
=> README: add link to German README

README.md
=> Readme: updates for alpha release wording & build documentation

CMakeLists.txt
"Les préludes", after Franz Liszt.
---
---
=> Kovri: update release version and codename
