monero-project/kovri

.codedocs, README.md
Use the CodeDocs.xyz GitHub integration to automatically build the
doxygen documentation.
Fixes monero-project/kovri#69
=> Add .codedocs file and CodeDocs badge to README.md

src/core/I2NPProtocol.cpp
* Added spec documentation
* Referencing #65 
Note: peer review would be appreciated before we merge this into master (@EinMByte).
=> I2NP: fix tunnel build request raw memory leak.

src/core/transport/SSUSession.cpp, src/core/transport/SSUSession.h
---
SSUSession: fill padding in SendSessionConfirmed.
* Resolves #65 
SSUSession: document SSU payload types. Refactor.
* Refactoring consisted of re-ordering function layout and fixing a few trivial style issues.
=> SSUSession: resolve #65 + document payload types.

src/client/I2PTunnel/I2PTunnel.cpp, src/core/transport/NTCP.cpp, src/core/transport/NTCP.h, src/core/transport/NTCPSession.cpp, src/core/transport/NTCPSession.h, src/core/transport/SSU.cpp, src/core/transport/SSU.h, src/core/transport/SSUData.cpp, src/core/transport/SSUSession.cpp, src/core/transport/SSUSession.h, src/core/transport/TransportSession.h, src/core/transport/Transports.cpp, src/core/transport/Transports.h, src/core/transport/UPnP.cpp, src/core/transport/UPnP.h
---
* Effects Transports/TransportSession, NTCP/SSU, UPnP
- SSU was left mostly alone because of #140
* Improve logging / add debugging output
- Create new Get/Set session-info logging handlers
* NTCPSession: fix …
=> Transports: fixes, refactor, improve logging.

src/core/transport/Transports.cpp
---
Only noticeable when shutting down the router or when running ```./kovri -h```. This is a simple fix. A real fix requires a better logging implementation.
=> Transports: fix SIGSEGV from LogPrint placement.

src/core/Garlic.h
=> Garlic: fix uninitialized padding in ElGamalBlock.

doc/CONTRIBUTING.md
=> Docs: add 'Proposals' and commit-title caveats to contributing guide.

src/core/Reseed.cpp
---
*Enter your pull request summary here*
This will fail in some locales, the list of which I am totally
unable to list. At least one Turkish one, I believe.
Fixes tests and main binary on Fedora.
=> Reseed: do not rely on [a-z] catching all letters

src/core/CMakeLists.txt, src/core/crypto/pimpl/supercop/ed25519/crypto_verify_32.h, src/core/crypto/pimpl/supercop/ed25519/verify.cpp
---
* Implements ```supercop-20141124/crypto_verify/32/ref/verify.c```
* Fixes #153
=> Crypto: use constant-time comparison in ed25519.

doc/STYLE.md
- I give this submission freely under BSD-3 license.
---
*Enter your pull request summary here*
Cpplint is now provided as a Python module with extra features
thanks to https://github.com/theandrewdavis/cpplint
This PR retargets ``development`` branch instead of ``master`` as in #230 . …
=> Docs: change links to cpplint project

.clang-format
---
It looks like the Kovri codebase is transitioning from one style to …
=> Add ClangFormat config for Google C++ Style

src/client/I2PControl/I2PControl.cpp, src/client/I2PControl/I2PControl.h, src/client/I2PService.h, src/client/I2PTunnel/I2PTunnel.cpp, src/client/I2PTunnel/I2PTunnel.h, src/client/I2PTunnel/SOCKS.h, src/core/Profiling.cpp, src/core/util/Filesystem.h, src/core/util/HTTP.cpp, src/core/util/ZIP.h
---
Verified compilation with Clang 3.8 on Ubuntu 16.04;
however, no …
=> Fix compilation with Clang 3.8

.travis.yml
---
Travis folks fixed the outdated certificate issues.
It would be best …
=> Coverity: Remove unnecessary certificate fetch

src/core/util/Filesystem.h
---
There's no need to be too general
with perfect forwarding of integral …
=> OS X: Fix StringStream::Seekg signature

.clang-format, doc/STYLE.md
---
Corresponding configurations for clang-format are provided.
These …
=> Style: Clarify deviations from the GCSG

doc/STYLE.md
---
* Enums should not need to be prefixed with e or e_
(it's bad enough …
=> Docs: update and clarify style guide. Refs #245.

.travis.yml, Doxyfile.in, cmake/UseDoxygen.cmake, doc/BUILDING.md
---
- The previous input filter was somehow preventing a fair amount of code
from being processed. We don't need the filter for now as its only
purpose was to showcase TODO's.
- Without …
=> Doxygen: remove input filter + fix input & CMake

Makefile, doc/BUILDING.md
---
- Needed for weidai11/cryptopp#232
- Remove requirement from docs
=> Build: add CXXFLAGS for clang/cryptopp to Makefile

Makefile
---
Until #317 is fixed, our Travis CI builds will be plagued with sporadic "failures" despite the build being successful.
Also note that I cannot reproduce such frequent failures on any …
=> Build: temporarily disable running tests after build

src/client/datagram.cc, src/client/datagram.h, src/core/i2np_protocol.cc, src/core/i2np_protocol.h, src/core/transport/ntcp_session.cc, src/core/tunnel/tunnel.cc
---
The message is refactored with a unique_ptr instead of a raw pointer that acts like a handle.
Releasable shared_ptr is implemented to make callback functions copy constructible.
This seems …
=> Refactor I2np protocol message with unique_ptr

src/core/util/mtu.cc
- [ x] I confirm.
---
This should take care of the error on coverity CID 135924
sockets on my server are not v6 they are v4 so I was not able to test this …
=> MTU: resolve CID 135924 (strncpy() not null-terminated). Refs #263.

src/core/identity.cc, src/core/router_context.cc, src/core/transport/ntcp.cc, src/core/transport/ntcp.h, src/core/transport/ssu.cc, src/core/transport/ssu.h, src/core/transport/ssu_session.cc, src/core/transport/ssu_session.h, src/core/transport/transports.cc, src/core/transport/transports.h
---
Sets EdDSA as the default signature type for all new RIs.
Sets SSU extended options.
Reduces the number of `io_service` objects and threads for transports to one: resolves #348.
=> Transports: implement #348, set SSU extended options, default EdDSA

src/client/client_context.cc, src/client/client_context.h, src/client/i2p_service.cc, src/core/identity.h, src/core/router_context.cc
---
Router is stable (aside from unrelated open issues), client/server tunnels fully functional.
I haven't look into this further, but current attempts with Ed result in non-functional …
=> Crypto: establish default client signing-key type

src/core/crypto/aes.h, src/core/crypto/pimpl/cryptopp/aes.cc
---
Successfully tested on both aesni enabled/disabled machines.
- static const for global bool type
- static is implied because this particular const type
exists in namespace but static const …
=> Crypto: minor fixes/refactor of AES-NI runtime check

src/core/router_context.cc
=> RouterContext: fix missing unique_ptr array when handling keys

src/app/daemon.cc, src/app/daemon_linux.cc, src/app/util/filesystem.cc, src/app/util/filesystem.h, src/client/address_book/storage.h, src/client/api/i2p_control/i2p_control.cc, src/core/router/context.cc, src/core/router/context.h, src/core/router/net_db/net_db.cc, src/core/router/profiling.cc, src/core/util/filesystem.cc, src/core/util/filesystem.h
---
Our data path / data dir is hardcoded, defined at compile time. There is
nothing flexible about it: once you start the router, you it will work
within the same data directory indefinitely …
=> App/Core: fix filesystem-related issues introduced in #414

CMakeLists.txt, src/core/crypto/impl/cryptopp/aes.cc, src/core/crypto/impl/cryptopp/tunnel.cc
---
- Fixes CMake for ARM, add compile-time patches for run-time AES-NI
- Preprocessor: also added MSVS macro for future MSVS testing
- Cleaned-up CMake / shared hardening flags with Clang
=> Build: fix ARMv7/8 builds. Fixes #384, refs #285

src/core/router/net_db/impl.cc, src/core/router/net_db/impl.h, src/core/router/transports/impl.cc
---
References commits in #444
NetDb: removed redundant file path checking for deleting a file
NetDb: variable styling fix to keep …
=> NetDb: refactor magic numbers + docs + style fixes. Refs #444

src/core/router/transports/ssu/session.cc, src/core/router/transports/ssu/session.h
---
A trivial patch until the bigger issue is resolved; this will prevent
sending SessionCreated to the very few routers who send bad?
SessionRequest data (at least uninitialized …
=> SSUSession: trivial patch to handle segfault in #119

src/core/router/garlic.cc, src/core/router/garlic.h
=> GarlicRoutingSession: use raw pointer for GarlicDestination. Fixes #342

src/core/crypto/rand.h, src/core/router/net_db/impl.cc, src/core/router/net_db/impl.h
- [X ] I confirm.
---
The original code was only randomly choosing a router indice on the first pass and if a router was not found then on the second pass it would start searching from the …
=> NetDb/Crypto: refactor rand router implementation

src/client/destination.cc, src/core/router/tunnel/impl.cc
---
Is called during tunnel pool deletion.
Also, reset thread pointer appropriately, add log message.
=> Tunnels: remove redundant stopping of tunnel pool

src/core/router/identity.cc, src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/session.cc
---
Patches #432 in terms of maintaining run-time operation. Several days of live testing + valgrind show that fix is legitimate.
=> IdentityEx/SSUPacketParser: throw for bad buffer + invalid length

src/core/router/tunnel/pool.cc
---
The magician struck again: casting `uint32_t` to `int` has undefined behaviour.
Forunately, the effect was trivial and only produced invalid ID's when logging.
=> TunnelPool: fix signed int overflow when logging tunnel test

src/core/router/tunnel/impl.cc, src/core/router/tunnel/pool.cc
---
Removes deprecated (in C++14) std::random_shuffle (refs #158)
=> Tunnel/TunnelPool: use CSPRNG shuffle

CMakeLists.txt, Makefile, src/app/CMakeLists.txt
---
Ubuntu32 CMake is misbehaving and not linking `-ldl` despite it being clearly marked to do so. I'll resolve the issue somehow before this is merged. Other than that, everything else checks …
=> Build: fix static bins for all supported platforms

CMakeLists.txt
It works at least on Fedora 21.
---
=> CMakeLists: allow GCC 4.9.2 (down from GCC 4.9.3)

src/core/crypto/impl/cryptopp/util/compression.cc, src/core/router/net_db/impl.cc
---
```
&anonimal       On an unrelated note, a trivial hotfix is working for #538: routers on all platforms are still online after ~22 hours; logs show success.
&anonimal       In hindsight, …
```
=> Crypto/NetDb: throw/catch cryptopp impl exception

src/client/proxy/http.cc, src/client/proxy/http.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/client/proxy/http.cc
=> HTTP Proxy : see #11 

.clang-format
- [x ] I confirm.
---
```
"commentPragma:
A regular expression that describes comments with special meaning, which should not be split into lines or …
```
=> clang-format :: fix mangled license

snap/kovri-wrapper, snap/snapcraft.yaml
---
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the …
=> Add the packaging metadata to build the kovri snap

.clang-format, CPPLINT.cfg, README.md, doc/STYLE.md
---
Reduces developer dependency on *our* style guide while
- strengthening our clang-format'er
- allowing new developer styles to flourish (with parameters)
- *giving-in* to more Google style …
=> Kovri: update clang-format and style guide

doc/USER_GUIDE.md, src/client/context.cc, src/client/context.h
---
Adds Base64 address output to text file for distribution + address book.
=> ClientContext/Docs: add Base64 to address text file + user-guide tunnel setup

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
---
Removes extra step to confirm and placeholder text
=> Repo: remove fluff from GitHub templates

doc/STYLE.md
---
---
Add a note about clang-format for vim on ubuntu 16
=> STYLE :: clang-format ubuntu 16 note

Makefile
- Updates cmake option to disable CPU opts for native arch
* Updates our Makefile
- Adds new library improvements/features (nothing major which relates to
Kovri-specific crypto)
---
---
=> Build: bump cryptopp to c90a631

tests/unit_tests/client/address_book/impl.cc
---
---
fix unmatched bracket in address book unit test
=> kovri-tests :: fix unmatched curly address book unit tests

pkg/kovri-bash.sh
This is a script for kovri command-line completion.
It's nice to have for packaging,
relevant to issue #362.
Adopted from [SCRAM](https://github.com/rakhimov/scram)
---
---
=> Packager: add bash completion script for kovri

pkg/kovri-bash.sh, src/app/config.cc, src/util/base.cc, src/util/main.cc
This additional information is helpful for deducing the hints.
Only bool and path arguments are added.
Adding type information with Boost program options
is verbose and repetitive due to lack of reflection.
Macros can help, but it is still ugly.
The refactoring removes
most hard-coded options in the completion script.
The suggestions are deduced from argument types (path, bool).
Issue #611 
---
- I accept that this submission may not be used and …
=> Program options arg types and Bash completion

src/client/reseed.cc, src/client/util/zip.cc, src/core/router/info.cc, src/core/router/info.h, src/core/util/filesystem.cc, src/core/util/filesystem.h
=> RouterInfo: refactor RI reader/parser

src/app/instance.cc, src/core/router/context.cc, src/core/router/context.h, src/core/router/info.cc, src/core/router/info.h, src/core/router/net_db/impl.cc, src/core/router/transports/impl.cc, src/core/router/transports/upnp.cc
WIP. Live tests pass. Referencing #617. This WIP is in pursuit of isolating #187.
**Note for any reviewers**: if skimming through the GitHub *"Files Changed"* tab, a clickable *"Large diffs are not loaded by default"* for `router/info.cc` is tucked into the diff.
---
- I give this submission freely under the BSD 3-clause …
=> RouterInfo: various refactoring

src/app/instance.cc
Fixes boost::bad_any_cast when supplying port
---
---
=> Instance: fix failed conversion when supplying port

src/core/router/info.cc, src/core/router/info.h, src/core/util/filesystem.cc, src/core/util/filesystem.h
WIP. Live tests pass. Referencing #617 #621. This WIP is in pursuit of isolating #187.
**Edit**: referencing #627
---
---
=> RouterInfo: refactor RI writer/creator + add docs

src/core/router/context.cc, src/core/router/info.cc, src/core/router/info.h, src/core/router/net_db/impl.cc, src/core/router/transports/impl.cc, src/core/router/transports/ssu/session.cc
Referencing #627. See commit log for details.
---
---
=> RouterInfo: caps refactoring

src/core/router/context.cc, src/core/router/context.h, src/core/router/info.cc, src/core/router/info.h, src/core/router/net_db/impl.cc, src/core/router/transports/impl.cc, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc
WIP. Lives tests pass with v6 enabled/disabled. Referencing #627.
---
---
=> RouterInfo: fixes + refactoring

src/core/router/context.cc, src/core/router/info.cc, src/core/router/info.h, src/core/router/net_db/impl.cc
WIP. Referencing #627.
---
---
=> RouterInfo: fixes + additions + refactoring

src/core/router/info.cc, src/core/router/info.h
WIP. Referencing #627.
---
---
=> RouterInfo: refactoring + documentation + optimizations + exception handling

pkg/kovri-install.sh
The current comparison between $_create_checksum_file and false at line 137 will always yield false since $_create_checksum_file at that point is either empty or true.  I am guessing that the intent is to fail if the caller supplies -c, but not -p.  If this is the case, then the script should fail if $_create_checksum_file is true, which is what this commit does.
(I ran into this when trying to port the install script to a shell different from bash for my own purposes.  Replacing the "== false" with "!= true", which is the right way to do this comparison results in the script failing the option checks when called without arguments from 'make install'.)
---
- I have read and understood the [Contributing …
=> kovri-install.sh: fix option checking

src/app/daemon.cc, src/client/api/i2p_control/session.cc, src/client/api/i2p_control/session.h, src/core/router/net_db/impl.cc, src/core/router/net_db/impl.h
WIP. Referencing #643 and #450.
---
---
=> NetDb: refactoring + traits

src/client/util/http.cc, src/client/util/http.h
=> HTTP :: use enums for status from cpp-netlib

src/app/daemon_linux.cc, src/client/api/i2p_control/session.cc, src/client/api/streaming.cc, src/core/crypto/impl/cryptopp/signature.cc, src/core/router/info.cc, src/core/router/net_db/impl.cc, src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc, src/core/router/transports/upnp.h, src/core/router/tunnel/config.cc
gcc 4.9 may not? zero-initialize subaggregates of aggregate with
implicitly-defined (default) ctor when using brace-elision (despite
brace-elision being allowed in c++14 (and subsequent gcc versions)).
For now, adding the extra braces ensures initialization and quiets
-Wmissing-field-initializers.
---
- I give this submission …
=> Kovri: remove brace-elision for array initialization

snap/snapcraft.yaml
Now that kovri is using submodules, this change is required to get them during the snapcraft pull.
---
---
=> snap: specify git as a source to get submodules

src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/packet.h
---
---
https://github.com/monero-project/kovri/blob/master/src/core/router/transports/ssu/session.cc#L474 overwrites the data being pointed by https://github.com/monero-project/kovri/blob/master/src/core/router/transports/ssu/session.cc#L466, so we were …
=> SSU: fix SessionCreated Alice's IP

src/core/router/transports/ssu/session.cc
---
---
Can't find this precisely in the specs, but [this is how](https://github.com/monero-project/kovri/blob/master/src/core/router/transports/ssu/session.cc#L402) the receiver is processing it (this difference between ProcessSessionCreated and …
=> SSU: fix SendSessionCreated endianness

src/core/router/transports/ssu/session.cc
---
---
Ref #140 
ProcessDecryptedMessage is processing encrypted data on hmac verif failure, leading most of the time to the error
>  InputByteStream: too many bytes to consume.
=> SSU: message validation process

src/core/router/transports/ssu/packet.h, src/core/router/transports/ssu/server.h, src/core/router/transports/ssu/session.cc
---
---
Ref #140 
IIUC, it should be 1502  and not 1500 
Jftr, in practice, AESAlignedBuffer has room for alignment (15 bytes) so the overflow should have been extremely rare (a packet with max mtu size + max alignment).
=> SSU: fix and document raw packet buffer size

src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/packet.h, src/core/router/transports/ssu/session.cc, src/core/util/byte_stream.cc, src/core/util/byte_stream.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/core/util/byte_stream.cc
---
---
IMHO, i think this is a better fix for #658 "design-wise" (with the disclamer that i'm usually not very good at design)
IIUC, the idea behind the builder is that all data are already available and we only need to find pointers to these data. The problem …
=> SSU: better fix for #658

src/core/util/byte_stream.cc, src/core/util/byte_stream.h, tests/unit_tests/core/util/byte_stream.cc
---
---
For `Util: OutputByteStream add check for empty data` : 
I saw in [std::memcpy spec](http://en.cppreference.com/w/cpp/string/byte/memcpy) : 
If either dest or src is a null pointer, the behavior is undefined, even if count is zero. 
But I would like to …
=> Util: ByteStream members init and unit-test

src/client/api/streaming.cc, src/client/proxy/socks.cc, src/core/router/identity.cc, src/core/router/info.cc
Note: GCC 7 will also recognize the [[clang::fallthrough]] attribute but
we currently avoid doing this because of the older compilers we use.
From https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html:
>C++17 provides a standard way to suppress the -Wimplicit-fallthrough
warning using [[fallthrough]]; instead of the GNU attribute. In C++11 or
C++14 users can use [[gnu::fallthrough]];, which is a GNU extension.
Instead of these attributes, it is also possible to add a fallthrough
comment to silence the warning. The whole body of the C or C++ style
comment should match the given regular expressions listed below. The
option argument n specifies what kind of comments are accepted:
---
- I have read and understood the …
=> Build: fix GCC 7 implicit fallthrough warnings

pkg/installers/kovri-install.sh
Fixes packaging for win32 nightly build.
---
---
=> Package: update program files path for win install

src/core/crypto/diffie_hellman.h, src/core/router/transports/ntcp/server.cc, src/core/router/transports/ntcp/session.cc, src/core/router/transports/ntcp/session.h, src/core/router/transports/session.h, src/core/util/byte_stream.cc
=> NTCPSession: fix max message size + Phase1/SessionRequest refactoring + trace log (Phase1/Phase2)/hex formatting cleanup

src/client/CMakeLists.txt, src/client/api/i2p_control/data.cc, src/client/api/i2p_control/data.h, src/client/api/i2p_control/server.cc, src/client/api/i2p_control/session.cc, src/client/api/i2p_control/session.h, src/client/util/json.cc, src/client/util/json.h, src/util/CMakeLists.txt, src/util/fuzz.cc, src/util/i2pcontrol.cc, src/util/i2pcontrol.h, src/util/i2pcontrol_client.cc, src/util/i2pcontrol_client.h, src/util/main.cc, tests/fuzz_tests/i2pcontrol.cc, tests/fuzz_tests/i2pcontrol.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/client/api/i2p_control/data.cc, tests/unit_tests/client/api/i2p_control/parser.cc
---
---
Ref #399 #383 
Here are some runtime examples : 
#!/bin/bash
./build/kovri-util control status $@
./build/kovri-util control version $@
./build/kovri-util control uptime $@
./build/kovri-util control reseed $@
./build/kovri-util control --method Echo …
=> I2PControl: rewrite/refactor + client api + kovri-util integration + unit-test + fuzz-test

src/core/crypto/aes.h, src/core/crypto/impl/cryptopp/aes.cc, src/core/router/transports/ntcp/session.cc, src/core/router/transports/ntcp/session.h
WIP. Refs #352.
**Edit**: also referencing #285.
---
---
=> Crypto/NTCP: annotate/refactor AES-256 expanded keysize + Phase2 Bob's IV offset

contrib/docker/Dockerfile_dev, contrib/docker/testnet.sh
---
---
To avoid rebuilding the docker image for each git revision, the user can now choose to "Use binaries from repo" during testnet creation.
To rebuild the binaries:
testnet.sh exec make
Or get a shell first:
testnet.sh exec sh
and then
make
=> Testnet: add new container for build

pkg/config/kovri.conf, src/app/config.cc, src/core/util/log.cc, src/util/main.cc
Will be useful when logging lower levels to a named pipe and/or if
auto-flushing is simply desired at any lower level.
---
---
=> Config: add automatic log flushing option

contrib/docker/fw_entrypoint.sh, contrib/docker/testnet.sh
---
---
This PR introduces 2 new vars:
- KOVRI_NB_BASE: number of instances (exactly like previously setup)
- KOVRI_NB_FW: new instances that are not in the reseed file and that are firewalled (basic setup: block incoming, allow outgoing) . It's done by overwriting the …
=> Testnet : add optional firewalled instances

README.md
RFC. Do we really need this? I think not.
The service appears useless. No better than GNU social - and has tighter speech restrictions.
Also, `@getkovri` on twitter gets 45 followers in just a couple of days but `@kovri@mastadon.social` only gets 2 (one a community member and the other appears to be a bot). Not to mention, mastodon keeps spamming my bitlbee with posts from instance admins of whom I'm not following.
In all, not worth maintaining IMHO but we can keep as 'reserved' account.
Referencing https://github.com/monero-project/meta/issues/113.
---
- I have checked that another pull-request for this purpose …
=> README: remove mastodon.social point of contact

contrib/docker/Dockerfile.dev.apache, contrib/docker/apache.entrypoint.sh, contrib/docker/testnet.sh, pkg/config/kovri.conf, src/app/config.cc, src/app/instance.cc, src/client/util/http.cc, src/core/router/context.cc, src/core/router/context.h
Also implements kovri `--enable-ssl` option.
Resolves #718.
---
---
=> Testnet: implement webserver for subscription publishing

src/util/CMakeLists.txt, src/util/cpuid.cc, src/util/cpuid.h, src/util/main.cc
TODO future:
-  Better error handling. Currently I’m returning zeros and empty strings when CpuId() fails. I think it would be better to check for CpuId() in the beginning and write an error if it fails.
---
---
=> kovri-util: add cpuid func

src/app/CMakeLists.txt, src/app/daemon.cc, src/app/daemon.h, src/app/daemon_linux.cc, src/app/daemon_win32.cc, src/app/instance.cc, src/app/instance.h, src/app/main.cc, src/client/CMakeLists.txt, src/client/instance.cc, src/client/instance.h, src/client/util/config.cc, src/client/util/config.h, src/core/CMakeLists.txt, src/core/instance.cc, src/core/instance.h, src/core/util/config.cc, src/core/util/config.h, src/core/util/exception.cc, src/core/util/exception.h, src/util/CMakeLists.txt, src/util/kovri.cc, src/util/kovri.h, src/util/main.cc
WIP.
- Works toward #350 and #351 
- Also works toward finishing-up #98 
- fe3321a's TODO makes reference to #533 
- #96 should be attainable now (though we wouldn't need to restart the daemon)
---
---
=> App/Client/Core: lib + instance work for prelim API

CMakeLists.txt, Makefile, contrib/CMakeLists.txt, contrib/python/CMakeLists.txt, contrib/python/kovri.cc, src/CMakeLists.txt
- Will aid in C++ API/testnet development; very much so for run-time testing
- This commit also includes necessary/related build changes
Essentially closes #86. Further API development is ongoing in #350 and #351.
---
---
=> Kovri: implement Boost.Python wrapper (PoC for prelim C++ API)

CMakeLists.txt
=> CMake: extend Boost.Python detection beyond Arch Linux

CMakeLists.txt
Not sure how that works if my PR is on-top of your PR.
---
---
=>  CMake: add Boost.Python detection for macOS

src/client/api/i2p_control/session.cc, src/client/reseed.cc, src/client/reseed.h, src/client/util/http.cc, src/core/instance.cc, src/core/router/context.cc, src/core/router/context.h, src/core/router/i2np.cc, src/core/router/info.cc, src/core/router/info.h, src/core/router/net_db/impl.cc, src/core/router/net_db/requests.cc, src/core/router/transports/impl.cc, src/core/router/transports/ntcp/session.cc, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/session.cc, src/core/router/transports/upnp.cc, src/core/router/tunnel/config.cc, src/core/router/tunnel/endpoint.cc, src/core/router/tunnel/impl.cc, src/core/router/tunnel/pool.cc, src/core/util/config.cc, src/core/util/filesystem.h, src/util/routerinfo.cc, src/util/routerinfo.h
WIP for #627 to make way for #350.
---
---
=> Core: WIP rewrite of router context and RI + related fixes

src/core/router/garlic.cc, src/core/router/i2np.cc
Referencing HackerOne report `#291489` and #511.
**Edit:** the H1 report also makes related references to #64, #65, #630, and monero-project/meta#83
---
---
=> Garlic: add check for potential clove buffer over-read 

pkg/installers/windows/Common.iss
With the help of the flag `ignoreversion` for `[Files]` section entries in the InnoSetup installer script the Windows installer now always replaces existing files with the corresponding files in the installer, regardless of file dates, version info in .exe headers, or file content, when updating / upgrading an existing installation.
This "hard replace" of every file is much more robust than the previous behaviour using flag `comparetimestamp,` and the only small downside seems to be somewhat longer installer execution times when upgrading.
This follows an identical switch for the Windows installer for Monero. This is also what the Windows .BAT file for installing Kovri that this installer replaced did anyway.
Note that `ignoreversion` would be very dangerous to use with files that might …
=> Windows installer: Switch from 'comparetimestamp' to 'ignoreversion'

contrib/testnet/testnet.sh, pkg/config/kovri.conf, src/client/reseed.cc, src/client/reseed.h, src/core/util/config.cc
for consistency + add to config file + minor update to config SSL option
(note: SSL enabled by default without config file).
---
---
=> Core: invert SU3 verification config logic

contrib/testnet/monitoring/collect.sh, contrib/testnet/monitoring/dashboards/backup.py, contrib/testnet/monitoring/dashboards/details-containers.json, contrib/testnet/monitoring/dashboards/details-netdb.json, contrib/testnet/monitoring/dashboards/instance-overview.json, contrib/testnet/testnet.sh
---
---
if `KOVRI_DISABLE_MONITORING` is set to `false`, it will create 4 additional containers:
- 1 for a time series database ([influxdb](https://www.influxdata.com/))
- 1 for collecting statistics from kovri instances via kovri-util
- 1 for collecting container statistics …
=> Testnet: add monitoring

contrib/testnet/testnet.sh, pkg/config/kovri.conf, src/client/util/http.cc, src/core/util/config.cc, src/core/util/filesystem.cc, src/core/util/filesystem.h
Since we don't actually use SSL (force of habit to lump TLS/HTTPS/OpenSSL into "SSL") and since we don't use TLS anywhere else outside of HTTP.
---
---
=> Kovri: clarify HTTPS nomenclature + log warning when not using HTTPS

src/core/router/identity.cc
Use the size parameter supplied to IdentityEx::ToBuffer() to ensure
the supplied buffer is large enough.
---
---
=> IdentityEx: lowerbounds check on buffer creation

CMakeLists.txt
NDEBUG especially needed to prevent potentially sensitive information
leakage in core dumps or by OS dump reporters when aborts are made by
posix assertions.
---
---
=> CMake: add NDEBUG flag for release builds

src/client/address_book/impl.cc
When decoding a base32 address, the full address was passed as argument to the decoder, instead of only the base32 subpart to decode.
Ex: Was trying to decode `uaknjcssainezmqcgfavwqsewu7nnuaakk2m7ywprcirra7m7tqa.b32.i2p` instead of just `uaknjcssainezmqcgfavwqsewu7nnuaakk2m7ywprcirra7m7tqa`
---
- I have [partially] read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I give this submission freely …
=> AddressBook: decode base32 substring from valid host name

src/core/crypto/radix.h
=> Radix: throw length error, not runtime, when decoding

src/core/crypto/impl/cryptopp/radix.cc
This is a time/space tradeoff, but it also provides one-time initialization while avoiding a race.
It should also clear https://github.com/weidai11/cryptopp/issues/562, https://github.com/monero-project/kovri/pull/788 and https://github.com/monero-project/kovri/pull/802 once and for all (famous last words).
I was not sure of the project's style regarding internal linkage and hiding names so things were added to an unnamed namespace. Feel free to modify it mercilessly.
---
- I have considered and confirmed that this submission will be …
=> Unroll DecodingLookupArray for Base32 and Base64 decoders

src/core/router/transports/ssu/session.cc
=> SSUSession: get intro key from IPv6 capable routers

CMakeLists.txt, src/core/router/context.cc, src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/packet.h, src/core/router/transports/ssu/session.cc, src/core/router/transports/ssu/session.h, src/core/util/byte_stream.cc, src/core/util/byte_stream.h
---
---
See git-log for details.
Resolves #213 (finally). Referencing https://github.com/monero-project/kovri/issues/433#issuecomment-321105373 and #140.
Requires merging of #828.
=> Kovri: implement SSU IPv6 peer testing + bump I2P router version to 0.9.27

src/client/proxy/http.cc, src/client/proxy/http.h, tests/unit_tests/client/proxy/http.cc
---
---
Part of #812, HTTPMessage::HandleJumpService now searches the HTTP URI for the `i2paddresshelper` parameter.
Unit test to ensure correct handling of valid jump service parameter.
Still requires unit tests for invalid parameters, and other failure cases.
=> HTTPMessage: refactor jump service parser + add test-cases

CMakeLists.txt, src/core/crypto/impl/cryptopp/elgamal.cc, src/core/router/transports/ssu/packet.h, src/core/router/tunnel/impl.h, src/core/util/mtu.h
---
---
Resolves #408. Referencing https://github.com/monero-project/kovri/issues/433#issuecomment-321105373.
=> Kovri: implement requisites for 0.9.28 + bump I2P router version to 0.9.28

src/client/proxy/http.cc, src/client/proxy/http.h, tests/unit_tests/client/proxy/http.cc
---
---
#837 has exposed a failed test-case introduced in #813. I wanted to get #813 merged because A) it didn't break functionality B) it didn't appear to break tests. Oddly, the tests were green before merging #813 and I didn't look too close nor build locally because I didn't …
=> HTTPProxy: unit-test rewrite + fix

src/client/address_book/impl.cc, src/client/address_book/impl.h, tests/unit_tests/client/address_book/impl.cc
---
---
Fixes #814
__edit__: HTTP Proxy is changed indirectly through the Address Book singleton the proxy uses to save jump service addresses.
=> AddressBook + HTTP Proxy: store only unique subscription addresses

src/core/router/context.cc, src/core/router/info.cc, src/core/router/info.h, src/core/util/config.cc, src/core/util/config.h, src/util/routerinfo.cc
---
---
Add to the existing --host parameter the capabilities to handle both ipv4 and ipv6 address
using a "," separator.
See #777
=> RouterInfo: Expand --host to take both ipv4 and ipv6 addresses.

src/core/util/filesystem.cc, src/core/util/filesystem.h
---
---
We don't really need VLA usage. Moreover, we can use copy elision optimization by fixing methods signature.
=> Get rid of VLA usage

src/core/router/transports/impl.cc, src/core/router/transports/impl.h, src/core/router/transports/ntcp/session.cc
They must be ephemeral. Resolves #368.
---
---
=> Transports: don't reuse DH keypairs

CMakeLists.txt, Makefile, contrib/python/CMakeLists.txt, src/CMakeLists.txt, src/app/CMakeLists.txt, src/client/CMakeLists.txt, src/core/CMakeLists.txt, src/util/CMakeLists.txt, tests/unit_tests/CMakeLists.txt
---
---
https://github.com/sakra/cotire
Right now cotire is enabled only for MSVC builds. This PR enables it for other platforms.
On the local machine, it reduces the build time by 2 times.
=> Build: Use cotire for all supported platforms

pkg/installers/kovri-install.sh
Fixes handling of 2 files during install/uninstall
- kovri-util: install when present, always try to uninstall
- kovri-bash.sh: was never uninstalled from ~/bin
Tested 'make install' and 'make uninstall' for targets
'make release' and plain 'make' (dynamic)
---
---
=> kovri-install.sh: refactor + fix

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
The contributor guide no longer exists.
---
---
=> Repo: update guide name in GitHub templates

src/core/crypto/aes.h, src/core/util/tag.h
This removes union-based alignment from:
- Tag
- AES buffer
---
---
=> Core: Use C++11 alignas to enforce data alignment

README.md
openssl is a cli tool.
libssl-dev is a development lib.
Not sure how in other distros (arch?).
---
---
=> README: Fix Ubuntu dep openssl -> libssl-dev

src/core/util/byte_stream.h, tests/unit_tests/core/util/byte_stream.cc
---
---
~~~Partial fix for #823.~~~
Checks that buffers passed to `kovri::core::InputByteStream::Read` are non-null.
=> InputByteStream: checks for null source buffer when reading

src/client/api/i2p_control/data.cc, src/client/api/i2p_control/data.h
Fix for Coverity Issue 175261.
I2PControlDataTraits::GetTrait throws std::domain_error on unknown
method. It gets called from I2PControlDataTraits::GetMethodFromString
which is marked as noexcept, and instead returns Method::Unknown.
Signed-off-by: Tadeas Moravec <ted@cryptosphere-systems.com>
---
- I give this submission freely under the BSD …
=> I2PControlDataTraits: Fix uncaught exception.

src/util/benchmark.cc, src/util/benchmark.h
private_key_* and public_key_* arguments were switched when calling
BenchmarkTest.
Fixes Coverity issue 175260.
---
---
=> Benchmark: BenchmarkTest with correct arguments.

src/core/router/identity.cc, src/core/router/identity.h, tests/unit_tests/core/router/identity.cc
---
---
Resolves TODO replacing `sprintf` with calls to standard library functions, and fixes gcc8 format truncation warning.
=> Identity: refactor routing key creation

CMakeLists.txt, Makefile, deps/CMakeLists.txt, pkg/config/kovri.conf, src/core/CMakeLists.txt, src/core/router/transports/impl.cc, src/core/router/transports/impl.h, src/core/router/transports/upnp.cc, src/core/router/transports/upnp.h, src/core/util/config.cc
---
---
Resolves #866.
Note: there is currently a UPnP runtime issue that prevents the app from exiting. That issue is unrelated to this PR.
=> Kovri: implement runtime UPnP + remove transports dtor stop call

src/app/daemon.cc, src/core/instance.cc, src/core/util/config.cc
Cleans up log output when calling arg help or invalid arg option.
Resolves #899.
---
---
=> Kovri: don't dispatch error_with_option_name

README.md
Requires monero-project/kovri-docs#53 , since i already added there the Italian translation of the README as example for translators and linked to it from this PR.
This PR introduce the possibility to add multilingual README localized in the available languages on getkovri.org. i also added ad 'kovri' header to make the style of the page more consistent, ready to change it if reputated unnecessary.
---
- I accept that this submission may not be used and that …
=> Add TOC linking to multilingual README

src/core/router/info.cc
Scalar variable transport was declared without an initializer, and later
used in a comparison.
Fixes Coverity #175247.
---
---
=> Router: Initialize a variable.

tests/unit_tests/client/address_book/impl.cc
---
---
Renames constructed entry objects for clarity, and resolves clang `-Wuninitialized` warning:
```
kovri/tests/unit_tests/client/address_book/impl.cc:177:51: warning: variable 'entry' is uninitialized when used within its own initialization [-Wuninitialized] …
```
=> Tests: fix BookEntry naming warning

src/client/proxy/http.cc, src/core/util/exception.cc
shared_from_this() can throw std::bad_weak_ptr if called on an
object that has never been shared in a shared_ptr. Throwing an exception in
a destructor crashes the program.
Not using HTTPProxyHandler with shared pointers is a serious bug and
the program probably should crash, but in a more controlled manner and
with an error message.
But in mainly silences Coverity #175240.
---
- I accept that this …
=> Proxy: Catch a potential exception in destructor.

src/core/router/net_db/impl.cc, src/core/router/net_db/impl.h, src/core/util/exception.cc, src/core/util/exception.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/core/router/net_db/impl.cc
---
---
A number of refactors to getting closest routers:
* Adds error handling for `CreateRoutingKey` callers.
* Excludes routers before considering them as closest candidates.
* Adds lock for `RouterInfo`s in `GetClosestNonFloodfill` to make calling the function thread-safe.
* …
=> NetDb: refactor getting closest routers

src/core/CMakeLists.txt, src/core/router/context.cc, src/core/router/i2np.cc, src/core/router/info.cc, src/core/router/info.h, src/core/router/net_db/impl.cc, src/core/util/buffer.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/core/util/buffer.cc
---
---
This was getting in the way of me finishing my `bandcaps` branch. Otherwise, I'd have left the TODO.
RouterInfo is still very messy. Pulling it apart and a writing unit-test will be beneficial. Referencing #627.
=> Core: create buffer utility class + buffer unit-test + RI buffer refactor

src/core/router/tunnel/impl.cc
There are two problems with the position of m_TransitTunnelsMutex:
1. Value of `it` might change between the condition
`it->second->GetCreationTime() + TUNNEL_EXPIRATION_TIMEOUT` and
erasing `it` from m_TransitTunnels
Hence we need a lock around the whole condition.
2. But the content of m_TransitTunnels might change during the cycle.
If ManageTransitTunnels runs twice in parallel, a tunnel can get
deleted in one loop, but be accessed in the other one.
Hence we need a lock around the whole cycle.
Coverity #151155
---
- I have checked that another pull-request …
=> Router: Fix lock in managing tunnels.

src/client/proxy/socks.cc
shared_from_this() can throw std::bad_weak_ptr if called on an
object that has never been shared in a shared_ptr. Throwing an exception
in a destructor crashes the program.
Not using SOCKSHandler with shared pointers is a serious bug and
the program probably should crash, but in a more controlled manner and
with an error message.
But in mainly silences Coverity #175240.
Same situation as in PR #923 . I just haven't noticed that while working on
that one.
---
- I have considered and …
=> Socks: Catch a potential exception in destructor.

tests/unit_tests/core/router/net_db/impl.cc
Was not rebased after the buffer refactor in #926
---
---
=> Tests: NetDb: update parameters when adding RI

CMakeLists.txt
Credit to iDunk. Referencing monero-project/meta#238
---
---
=> CMake: fix the MinGW-w64 static build

contrib/testnet/Dockerfiles/Dockerfile.alpine, contrib/testnet/Dockerfiles/Dockerfile.arch, contrib/testnet/monitoring/collect.sh, contrib/testnet/testnet.sh
---
---
Number of small refactors to make creating and using the testnet easier:
* Fixes issues with user permissions between Docker host and containers
* Enables dynamic builds for testnets based on the Arch Dockerfile
* Fixes Python syntax bug if Docker host is running Python3
* …
=> Testnet: refactor testnet script and Dockerfiles

src/client/address_book/impl.cc, src/client/address_book/impl.h, src/client/address_book/storage.cc, src/client/address_book/storage.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/client/address_book/impl.cc, tests/unit_tests/client/address_book/storage.cc
---
---
First steps toward implementing #337. 
Default, user, and private subscription types will be used for their respective subscription files (`hosts.txt`, `user_hosts.txt`, and `private_hosts.txt`).
All publisher subscription files will save their unique addresses into the …
=> AddressBook: create multiple subscription map

CMakeLists.txt, src/core/router/info.cc, src/core/router/info.h, src/core/router/transports/impl.cc, src/core/router/transports/impl.h
---
---
Live tests pass, and client tunnels complete successfully. `RI`s with introducers are successfully parsed.
Can add unit-tests, but requires changing `ParseRouterInfo` from private to protected/public access.
Referencing #433.
=> Kovri: implement requisites for 0.9.32 + bump I2P router version to 0.9.32

CMakeLists.txt, src/core/router/info.cc, src/core/router/info.h, src/core/router/transports/impl.cc, src/core/router/transports/impl.h
---
---
Requires merging of #931 and https://github.com/coneiric/kovri/pull/1.
Resolves #433.
=> Kovri: bump I2P router version to 0.9.35 

src/core/router/info.cc, src/core/router/info.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/core/router/info.cc
---
---
Moves `RouterInfo` signing into creation, before converting to a buffer. Adds signature verification and unit-test.
=> RouterInfo: refactor signature creation and verification

README.md
This come along with ~~monero-project/kovri-docs#55 and should perhaps not be merge before~~ monero-project/kovri-docs#58 and should be merge at the same moment.
=> Readme updated with French Link.

contrib/testnet/testnet.sh
Help details were pulled from monero-project/kovri-docs#56
---
---
=> Testnet: add default grafana user + grafana to help

CMakeLists.txt, contrib/python/CMakeLists.txt
=> CMake: fix shared lib when using Boost.Python

src/core/router/transports/ssu/session.cc
Address is checked in GetIntroKey so the chances of running into the new
assert are negligible. But Coverity is right, the potential is nonzero.
Silences Coverity #183014.
---
---
=> Router ssu session: Fix potential null dereference

src/core/router/transports/ssu/session.cc
Maybe there should be `&&` instead of `||`. But it doesn't really matter, because this situation is handled by the `default` branch of the following switch statement.
Coverity #183013
---
---
=> SSU: Remove assert that's always true.

src/client/api/streaming.cc, tests/unit_tests/CMakeLists.txt, tests/unit_tests/client/api/streaming.cc
---
---
Use empty brace-initialization to default construct the current remote lease, and prevent a null buffer assertion firing.
Resolves #948.
=> Stream: default construct current remote lease

src/client/tunnel.cc, src/client/tunnel.h, src/core/router/identity.cc, src/core/router/identity.h, src/core/router/info.cc, tests/unit_tests/core/router/identity.cc, tests/unit_tests/core/router/identity.h, tests/unit_tests/core/router/net_db/impl.cc, tests/unit_tests/core/router/transports/ssu/packet.cc
=> Kovri: add ident base32 conversions + base32/64 tests, implement HTTP server tunnel X-I2P headers

src/client/destination.cc, src/core/router/transports/ssu/packet.cc, src/core/router/transports/ssu/session.cc, src/core/router/tunnel/config.cc, src/core/util/byte_stream.h, tests/unit_tests/core/util/byte_stream.cc
Use counter as index into the internal stream buffer, and use member functions for access.
References #823
---
---
=>  Bytestream: data pointer refactor, add tellp + related SSU refactor

pkg/config/tunnels.conf, src/client/util/parse.cc, src/client/util/parse.h, tests/unit_tests/client/util/parse.cc
=> Client: allow more hash types for server tunnel ACL

README.md
Currently the link to Moneropedia is redirected to Moneropedia's index page (https://getmonero.org/resources/moneropedia/).
---
---
=> README: update Moneropedia link to Kovri entry

pkg/installers/kovri-install.sh
Fixed invocation of the cp command. The Linux nightly package was almost empty,
it only contained pkg/client/, INSTALL.txt, and kovri-install.sh.
---
---
=> Installer: Fix building package on Linux.

Makefile
Fixes build on systems with default non-bash shells.
---
---
=> Build: set make shell to bash

src/core/crypto/impl/cryptopp/signature.cc
The verifier assertion won't allow the verifier to simply return, from
which we then throw accordingly. The signer assertion should be removed
because we throw on bad signing anyway.
Closes #981.
---
---
=> Crypto: remove ed25519 assertions

src/core/router/context.cc, src/core/router/info.cc, src/core/router/info.h, src/core/router/transports/impl.cc, src/core/router/transports/impl.h, src/core/router/transports/ssu/data.cc, src/core/router/transports/ssu/data.h, src/core/router/transports/ssu/server.cc, src/core/router/transports/ssu/server.h, src/core/router/transports/ssu/session.cc, src/core/router/transports/ssu/session.h, tests/unit_tests/core/router/info.cc
---
---
Resolves #840.
Note: this PR decided to side-step most of the pre-fork issues mentioned in https://github.com/monero-project/kovri/issues/840#issuecomment-406165876 in favor of resolving a few immediate ones (including the adjusting of appropriate SSU packet size).
=> Core: use IPv6 address object when expected + add test cases

Makefile
Because of how our nightly builds are rigged, the build will "fail" when
running `make doxygen`, so this fix can't wait until after release.
We don't need another rc when this is merged because this is only needed for buildbot and the website. We can go directly to release next week (pending any other unforeseen issues).
---
- I give this …
=> Makefile: fix doxygen target (requires CMake)

src/core/router/context.h
Prevents boost::bad_any_cast by using the correct variable_map entry.
Resolves #990
---
---
=> NetDB: correct floodfill context option

src/core/router/transports/ssu/session.cc
---
---
Resolves #997 (should).
As for the need to throw for all null deference checks, I'll provide a better solution when I return so we don't have to litter the code with throws for every pointer.
=> SSUSession: get either IPv4/6 intro key from remote

CMakeLists.txt
Clang release builds are too aggressive with `-O3` optimizations, and cause runtime errors.
Allows for Clang release builds, referencing #993.
---
---
=> Build: remove aggressive optimizations for clang
